services:
    _defaults:
        autoconfigure: true

    terminal42_url_rewrite.listener.rewrite_container:
        class: Terminal42\UrlRewriteBundle\EventListener\RewriteContainerListener
        public: true
        arguments:
            - "@terminal42_url_rewrite.qr_code_generator"
            - "@router"
            - "%kernel.cache_dir%"
            - "@contao.framework"
            - "@router.expression_language_provider"
            - "@filesystem"
